ADVICES = [
    # Happy (0)
    {'advice': "If it’s not a 'hell yes,' it’s a 'no'", 'category': 0},
    {'advice': "Go outside for a walk", 'category': 0},
    {'advice': "Move your body – Dance, walk, stretch.", 'category': 0},
    {'advice': "Be around good vibes = positive mood.", 'category': 0},
    {'advice': "Practice gratitude – Think of 3 things you’re thankful for.", 'category': 0},
    {'advice': "Do something kind – Helping others boosts your own mood.", 'category': 0},
    {'advice': "Be silly – Laugh, play, let go.", 'category': 0},
    {'advice': "Listen to your favorite music and vibe.", 'category': 0},
    {'advice': "Capture the moment – take a photo or write a memory.", 'category': 0},
    {'advice': "Smile at a stranger – it’s contagious.", 'category': 0},
    {'advice': "Dance like no one’s watching.", 'category': 0},
    {'advice': "Celebrate small wins – they count too.", 'category': 0},
    {'advice': "Compliment someone – it’ll make both of you feel good.", 'category': 0},
    {'advice': "Make a list of things that make you happy.", 'category': 0},
    {'advice': "Laugh at something dumb – humor heals.", 'category': 0},

    # Sad (1)
    {'advice': "Write down your thoughts", 'category': 1},
    {'advice': "Feel it – Don’t bottle it up.", 'category': 1},
    {'advice': "Talk to someone – You're not alone.", 'category': 1},
    {'advice': "Write it out – Journaling helps clear your mind.", 'category': 1},
    {'advice': "Rest – Sadness can be exhausting.", 'category': 1},
    {'advice': "Be gentle with yourself – Healing takes time.", 'category': 1},
    {'advice': "Cry if you need to – it helps", 'category': 1},
    {'advice': "Watch a movie that comforts you.", 'category': 1},
    {'advice': "Let yourself do nothing for a while.", 'category': 1},
    {'advice': "Avoid judging your emotions – just feel.", 'category': 1},
    {'advice': "Drink something warm – tea or cocoa helps.", 'category': 1},
    {'advice': "Listen to music that gets your feelings out.", 'category': 1},
    {'advice': "Take a hot shower – wash the weight off.", 'category': 1},
    {'advice': "Say something kind to yourself out loud.", 'category': 1},
    {'advice': "Breathe deeply – in through your nose, out through your mouth.", 'category': 1},

    # Stressed (2)
    {'advice': "Drink water before you're thirsty", 'category': 2},
    {'advice': "Take breaks – burnout sucks", 'category': 2},
    {'advice': "Unplug from your phone for 30 minutes.", 'category': 2},
    {'advice': "Make a to-do list – clear your head.", 'category': 2},
    {'advice': "Try a 5-minute meditation.", 'category': 2},
    {'advice': "Stretch your body slowly – release tension.", 'category': 2},
    {'advice': "Say 'no' if it’s too much – protect your peace.", 'category': 2},
    {'advice': "Take 3 deep breaths. Do it again.", 'category': 2},
    {'advice': "Do one thing at a time – multitasking is a myth.", 'category': 2},
    {'advice': "Go outside – fresh air resets your brain.", 'category': 2},
    {'advice': "Laugh at a meme – yes, seriously.", 'category': 2},
    {'advice': "Change your scenery – move rooms or go outside.", 'category': 2},
    {'advice': "Repeat this: 'I don’t need to do it all right now.'", 'category': 2},
    {'advice': "Close your eyes for a moment and let go.", 'category': 2},
    {'advice': "Organize your space – clutter adds stress.", 'category': 2},

    # Motivated (3)
    {'advice': "Start before you feel ready", 'category': 3},
    {'advice': "Remember why you started", 'category': 3},
    {'advice': "Your future self will thank you.", 'category': 3},
    {'advice': "Progress > perfection", 'category': 3},
    {'advice': "Set one goal and crush it today.", 'category': 3},
    {'advice': "You’ve done hard things before – you got this.", 'category': 3},
    {'advice': "Small steps still move you forward.", 'category': 3},
    {'advice': "Imagine the results – feel it, see it, do it.", 'category': 3},
    {'advice': "Energy follows action – just begin.", 'category': 3},
    {'advice': "You're not alone – someone out there believes in you.", 'category': 3},
    {'advice': "Read one quote that fires you up.", 'category': 3},
    {'advice': "Eliminate one distraction – stay locked in.", 'category': 3},
    {'advice': "Check in with your goals – are they still exciting?", 'category': 3},
    {'advice': "Push a little further – you're closer than you think.", 'category': 3},
    {'advice': "Keep showing up – that’s where growth lives.", 'category': 3},
]
