ADVICES = [
    {'advice': "If it’s not a 'hell yes,' it’s a 'no'", 'category': 0},
    {'advice': "Go outside for a walk", 'category': 0},
    {'advice': "Move your body – Dance, walk, stretch.", 'category': 0},
    {'advice': "Be around good vibes = positive mood.", 'category': 0},
    {'advice': "Practice gratitude – Think of 3 things you’re thankful for.", 'category': 0},
    {'advice': "Do something kind – Helping others boosts your own mood.", 'category': 0},
    {'advice': "Be silly – Laugh, play, let go.", 'category': 0},
    {'advice': "Write down your thoughts", 'category': 1},
    {'advice': "Feel it – Don’t bottle it up.", 'category': 1},
    {'advice': "Talk to someone – You're not alone.", 'category': 1},
    {'advice': "Write it out – Journaling helps clear your mind.", 'category': 1},
    {'advice': "Rest – Sadness can be exhausting.", 'category': 1},
    {'advice': "Be gentle with yourself – Healing takes time.", 'category': 1},
    {'advice': "Cry if you need to – it helps", 'category': 1},
    {'advice': "Drink water before you're thirsty", 'category': 2},
    {'advice': "Take breaks – burnout sucks", 'category': 2},
    {'advice': "Start before you feel ready", 'category': 3},
    {'advice': "Remember why you started", 'category': 3},
]
